// Modifications Copyright(C) [2025] Advanced Micro Devices, Inc. All rights reserved)

// SPDX-FileCopyrightText: © 2025 Allegro DVT <github-ip@allegrodvt.com>
// SPDX-License-Identifier: MIT

/* This file was generated by configure. DO NOT MODIFY */

#pragma once

#ifdef HAVE_VCU_CTRLSW
#include "config_vcu1.h"
#endif
#ifdef HAVE_VCU2_CTRLSW
#include "config_vcu2.h"
#endif
