if(NOT RUN_HOOK_ONCE_opencv_vcucodec)
    message(STATUS "Run hook: INIT_MODULE_SOURCES_opencv_vcucodec.cmake")
    if (HAVE_VCU_CTRLSW)
        message(STATUS "  HAVE_VCU_CTRLSW: ${HAVE_VCU_CTRLSW}")
        ocv_list_filterout(OPENCV_MODULE_${the_module}_SOURCES "/encoder/")
    endif()
    if (HAVE_VDU_CTRLSW)
        message(STATUS "  HAVE_VDU_CTRLSW: ${HAVE_VDU_CTRLSW}")
        ocv_list_filterout(OPENCV_MODULE_${the_module}_SOURCES "/encoder/")
        ocv_list_filterout(OPENCV_MODULE_${the_module}_SOURCES "/encoder_vcu1/")
    endif()
    if (HAVE_VCU2_CTRLSW)
        message(STATUS "  HAVE_VCU2_CTRLSW: ${HAVE_VCU2_CTRLSW}")
        ocv_list_filterout(OPENCV_MODULE_${the_module}_SOURCES "/encoder_vcu1/")
    endif()

    set(RUN_HOOK_ONCE_opencv_vcucodec TRUE)

#    ocv_list_filterout(OPENCV_MODULE_${the_module}_SOURCES "/encoder/")
#    ocv_list_filterout(OPENCV_MODULE_${the_module}_HEADERS "/encoder/")
#    message(STATUS ${OPENCV_MODULE_${the_module}_SOURCES})
else()
    message(STATUS "Skip hook: INIT_MODULE_SOURCES_opencv_vcucodec.cmake")
    #message(STATUS "  HAVE_VCU_CTRLSW: ${HAVE_VCU_CTRLSW}")
    #message(STATUS "  HAVE_VDU_CTRLSW: ${HAVE_VDU_CTRLSW}")
    #message(STATUS "  HAVE_VCU2_CTRLSW: ${HAVE_VCU2_CTRLSW}")
endif()